### ISSUE TITLE
Recompute table using specific formula

### ISSUE THREAD

**Issue by filipelbc** [filipelbc/orgmode.vim#17]
If a table has many formula lines, the first one is used by default.

How to use another one? In Emacs you can just press "c-c c-c" on the formula to use it.

**Comment by ebellani** [comment]
https://github.com/jwiegley/org-mode/blob/433103fc5e5bb6d401e37707703a652683b859eb/lisp/org-table.el#L3175

**Comment by ebellani** [comment]
@filipelbc

**Comment by filipelbc** [comment]
Thanks.

`org-table-calc-current-TBLFM`
